
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

 contract SampleToken {


    struct Token {
        string name;
        uint power;
    }

    Token[] tokensArr;
    mapping (uint => uint) tokenToOwner;

    function createToken (string name, uint power) public{
        tvm.accept();
        tokensArr.push(Token(name,power));
        uint keyAsLastNum = tokensArr.length - 1;
        tokenToOwner[keyAsLastNum] = msg.pubkey();
    }

    function getTokenOwner(uint tokenId) public view returns(string tokenName, uint tokenPower){
        tvm.accept();
        tokenName = tokensArr[tokenId].name;
        tokenPower = tokensArr[tokenId].power;
    }

    function ChangeOwner(uint tokenId,uint pubKeyOfNewOwner) public {
        require(msg.pubkey() == tokenToOwner[tokenId], 101);
        tvm.accept();
        tokenToOwner[tokenId] = pubKeyOfNewOwner;
    }

    function ChangePower(uint tokenId,uint power) public {
        require(msg.pubkey() == tokenToOwner[tokenId], 101);
        tvm.accept();
        tokensArr[tokenId].power = power;
    }
    
    
}
