
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

// This is class that describes you smart contract.
contract queueStore {
 
    string[] public customers;

    function addCustomer(string name) public returns (string) {
        tvm.accept();
        customers.push(name);
    }

    function delCustomer() public returns (uint) {
        tvm.accept();
        for (uint i=1; i<=customers.length-1; i++) {
            customers[i-1] = customers[i];
        }
        customers.pop();
    }


}
